{{- if eq .Values.global.environment "localdev"}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "airflow.fullname" . }}-logs
  labels:
{{ include "airflow.labels" . | indent 4 }}
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: {{ .Values.airflowPath }}{{ .Values.airflow.mount.subPath.logs }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "airflow.fullname" . }}-logs
  labels:
{{ include "airflow.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 8Gi
  volumeName: {{ include "airflow.fullname" . }}-logs
{{- end}}